using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerSwerveInputHandler : MonoBehaviour
{
    private float lastFrameFingerPositionX;
    public float MoveFactorX { get; private set; }

    private void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            lastFrameFingerPositionX = Input.mousePosition.x;
        }
        else if (Input.GetMouseButton(0))
        {
            MoveFactorX = Input.mousePosition.x - lastFrameFingerPositionX;
            lastFrameFingerPositionX = Input.mousePosition.x;
        }
        else if (Input.GetMouseButtonUp(0))
        {
            MoveFactorX = 0f;
        }
    }
}
